### PR TITLE
refine ver01: upgrade stx-ceph from v10.2.6 to v13.2.2

### PR DESCRIPTION
**Pull request by iotcg**
Rebase all patches to be on the latest stx-ceph/v13.2.2 after build process patches(https://github.com/starlingx-staging/stx-ceph/pull/17/commits) have been merged.

### CODE REVIEW

**Comment by iotcg** [comment]
@oponcea Please help review these patches when you're available.
We're verifying these patches.

**Comment by iotcg** [comment]
@oponcea 
We haven't port below change into this PR:
81 + #%global _libexecdir %{_exec_prefix}/lib
82 + %global _libexecdir %{_libdir}

It'll hit build error if we port them into the source code.

**Comment by dtroyer** [comment]
Please, I am not going to accept this sort of commit message.  I have asked multiple times, please include the relevant information in these commit messages that describe what the commit does.  Nobody outside Wind River or Intel has access to any of the historical information regarding the reasons or purpose of these commits, the commit log is the only public documentation.

**Comment by iotcg** [comment]
@dtroyer We're working with WindRiver to debug to make stx-ceph/v13.2.2 work with these patches.
@oponcea Do you agree with that we merge these patches firstly and go on debugging the problems in the system? It could avoid times of doing patch rebase. If yes, I'll resubmit the PR with clear commit message.

**Comment by oponcea** [comment]
We should not merge the patches till they pass sanity else it will impact all community members. Also, Ceph is becoming the default backend so it has to pass sanity first.

Ovidiu
________________________________

**Comment by iotcg** [comment]
@dtroyer Sure. The critical patches should be merged after sanity check.
BTW, Dean advice the patches could be divided into some groups and merge some group to avoid review time. Do you want to do this? I'm OK to review all patches at one time or merge some group first.

**Pull request closed without merging**
